version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  disable:
    - lll
    - mnd
  settings:
    dupl:
      threshold: 150
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Error return value of .(l.Sync|.*Close|.*Flush|os\.Remove(All)?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: exported method (.*\.MarshalJSON|.*\.UnmarshalJSON) should have comment or be unexported
      - path: (.+)\.go$
        text: 'shadow: declaration of "err" shadows declaration.*'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ewohltman/ephemeral-roles
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
